### ISSUE TITLE
On repos with many commits, gigantic amounts of memory are needed

### ISSUE THREAD

**Issue by flaviusb** [flaviusb/git-read-to-cloudefs#1]
When running this on the rails git repo, after running for about three days this crash happens:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:669)
	at java.io.StringWriter.toString(StringWriter.java:210)
	at kotlinx.serialization.json.JSON.stringify(JSON.kt:39)
	at org.fejoa.repository.ChunkStoreBranchLog.write(ChunkStoreBranchLog.kt:159)
	at org.fejoa.repository.ChunkStoreBranchLog.add(ChunkStoreBranchLog.kt:107)
	at org.fejoa.repository.ChunkStoreBranchLog.add(ChunkStoreBranchLog.kt:98)
	at org.fejoa.repository.ChunkStoreBranchLog.add(ChunkStoreBranchLog.kt:94)
	at org.fejoa.repository.Repository.commitInternal(Repository.kt:439)
	at org.fejoa.repository.Repository$commit$2.doResume(Repository.kt:393)
	at org.fejoa.repository.Repository$commit$2.invoke(Repository.kt)
	at org.fejoa.repository.Repository$commit$2.invoke(Repository.kt:112)
	at org.fejoa.support.SuspendQueue$runSync$$inlined$suspendCoroutine$lambda$1.doResume(SuspendQueue.kt:18)
	at org.fejoa.support.SuspendQueue$runSync$$inlined$suspendCoroutine$lambda$1.invoke(SuspendQueue.kt)
	at org.fejoa.support.SuspendQueue$runSync$$inlined$suspendCoroutine$lambda$1.invoke(SuspendQueue.kt:12)
	at org.fejoa.support.SuspendQueue$triggerWork$1.doResume(SuspendQueue.kt:51)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedKt.resumeCancellable(Dispatched.kt:208)
	at kotlinx.coroutines.experimental.CancellableKt.startCoroutineCancellable(Cancellable.kt:34)
	at kotlinx.coroutines.experimental.CoroutineStart.invoke(CoroutineStart.kt:113)
	at kotlinx.coroutines.experimental.BuildersKt.launch(Builders.kt:66)
	at kotlinx.coroutines.experimental.BuildersKt.launch$default(Builders.kt:58)
	at org.fejoa.support.SuspendQueue.triggerWork(SuspendQueue.kt:48)
	at org.fejoa.support.SuspendQueue.scheduleUnchecked(SuspendQueue.kt:38)
	at org.fejoa.support.SuspendQueue.access$scheduleUnchecked(SuspendQueue.kt:12)
	at org.fejoa.support.SuspendQueue.runSync(SuspendQueue.kt:16)
	at org.fejoa.repository.Repository.commit(Repository.kt:392)
	at net.flaviusb.gitreadtocloudefs.GitReadToCloudEFS$stuff$my_hash$1.doResume(gitreadtocloudefs.kt:125)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
	at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:147)
```

**Comment by flaviusb** [comment]
The repo that triggered this was https://github.com/rails/rails
